name: Daily PO Run

on:
  schedule:
    - cron: "0 7 * * *"  # щодня о 07:00 UTC
  workflow_dispatch: {}

jobs:
  run-po:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prepare env
        env:
          SUPPLIER_EMAIL: ${{ secrets.SUPPLIER_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          FROM_EMAIL_APP_PASSWORD: ${{ secrets.FROM_EMAIL_APP_PASSWORD }}
          DRY_RUN: ${{ secrets.DRY_RUN }}
        run: |
          echo "SUPPLIER_EMAIL=${SUPPLIER_EMAIL}" >> $GITHUB_ENV
          echo "FROM_EMAIL=${FROM_EMAIL}" >> $GITHUB_ENV
          echo "FROM_EMAIL_APP_PASSWORD=${FROM_EMAIL_APP_PASSWORD}" >> $GITHUB_ENV
          echo "DRY_RUN=${DRY_RUN}" >> $GITHUB_ENV
      - name: Run CLI (demo на sample_data)
        run: |
          python cli.py --sales sample_data/sales.csv --inventory sample_data/inventory.csv --supplier-email "${{ env.SUPPLIER_EMAIL }}"