name: Daily PO Run

on:
  schedule:
    - cron: "0 7 * * *"   # щодня о 07:00 UTC (10:00 за Києвом)
  workflow_dispatch: {}

jobs:
  run-po:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare env
        env:
          SUPPLIER_EMAIL: ${{ secrets.SUPPLIER_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          FROM_EMAIL_APP_PASSWORD: ${{ secrets.FROM_EMAIL_APP_PASSWORD }}
          DRY_RUN: ${{ secrets.DRY_RUN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SALES_CSV_URL: ${{ secrets.SALES_CSV_URL }}
          INVENTORY_CSV_URL: ${{ secrets.INVENTORY_CSV_URL }}
        run: |
          echo "SUPPLIER_EMAIL=${SUPPLIER_EMAIL}" >> $GITHUB_ENV
          echo "FROM_EMAIL=${FROM_EMAIL}" >> $GITHUB_ENV
          echo "FROM_EMAIL_APP_PASSWORD=${FROM_EMAIL_APP_PASSWORD}" >> $GITHUB_ENV
          echo "DRY_RUN=${DRY_RUN}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}" >> $GITHUB_ENV
          echo "SALES_CSV_URL=${SALES_CSV_URL}" >> $GITHUB_ENV
          echo "INVENTORY_CSV_URL=${INVENTORY_CSV_URL}" >> $GITHUB_ENV

      - name: Run CLI (use URLs if set, otherwise sample_data)
        run: |
          set -e
          if [ -n "${SALES_CSV_URL}" ]; then SALES_ARG="${SALES_CSV_URL}"; else SALES_ARG="sample_data/sales.csv"; fi
          if [ -n "${INVENTORY_CSV_URL}" ]; then INV_ARG="${INVENTORY_CSV_URL}"; else INV_ARG="sample_data/inventory.csv"; fi
          echo "Using sales: ${SALES_ARG}"
          echo "Using inventory: ${INV_ARG}"
          python cli.py --sales "${SALES_ARG}" --inventory "${INV_ARG}" --supplier-email "${SUPPLIER_EMAIL}"
