- name: Run IMAP runner
  env:
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
    IMAP_HOST:          ${{ secrets.IMAP_HOST }}
    IMAP_USER:          ${{ secrets.IMAP_USER }}
    IMAP_PASSWORD:      ${{ secrets.IMAP_PASSWORD }}
    IMAP_FOLDER:        ${{ secrets.IMAP_FOLDER }}
    IMAP_FILENAME_REGEX:${{ secrets.IMAP_FILENAME_REGEX }}
    OUT_DIR: out
    DRY_RUN: "0"
  run: |
    python github_runner_imap.py
