name: Generate PO (IMAP → Telegram)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl xlrd==2.0.1 requests python-dotenv

      - name: Run IMAP runner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          IMAP_HOST:          ${{ secrets.IMAP_HOST }}
          IMAP_USER:          ${{ secrets.IMAP_USER }}
          IMAP_PASSWORD:      ${{ secrets.IMAP_PASSWORD }}
          IMAP_FOLDER:        ${{ secrets.IMAP_FOLDER }}
          IMAP_FILENAME_REGEX: ${{ secrets.IMAP_FILENAME_REGEX }}  # ← ОБОВʼЯЗКОВО з пробілом після :
          OUT_DIR: out
          DRY_RUN: "0"
        run: python github_runner_imap.py

      - name: Upload CSV artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: beer-pos
          path: out/*.csv
          if-no-files-found: warn
